### ISSUE TITLE
AVR128DB28 attempting change a fuse setting using (otherwise working) serialUPDI adapter (2/10/2022)

### ISSUE THREAD

**Issue by wb0gaz** [mariusgreuel/avrdude#8]
SerialUPDI adapter was built using FTDI232 module and is working properly to read flash memory, write flash memory, and read fuse value with target AVR128DB28 (supply voltage 3.6VDC from USB serial adapter.)

Issue: Writing/changing fuse value (in this case, BOOTSIZE fuse at 0x1058 per avrdude.conf is to be changed from factory default value of 0x20 to user-specified value of 0x00) fails to verify (and does not change value when subsequently read on a different UPDI adapter device type.)

Command:

_>avrdude -c serialupdi -p avr128db28 -P com7 -U bootsize:w:0x00:m_

Response:

avrdude: UPDI link initialization OK
avrdude: NVM type 2: 24-bit, word oriented write
avrdude: Entering NVM programming mode
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.05s

avrdude: Device signature = 0x1e970e (probably avr128db28)
avrdude: reading input file "0x00"
avrdude: writing bootsize (1 bytes):

Writing | ################################################## | 100% 0.03s

avrdude: 1 bytes of bootsize written
avrdude: verifying bootsize memory against 0x00:

Reading | ################################################## | 100% 0.01s

avrdude: verification error, first mismatch at byte 0x0000
         0x20 != 0x00
avrdude: verification error; content mismatch

avrdude: safemode: Fuses OK (E:FF, H:FF, L:FF)
avrdude: Leaving NVM programming mode

avrdude done.  Thank you.

**Comment by mariusgreuel** [comment]
@wb0gaz This problem is most likely not related to the Windows port. Can you please move your issue to https://github.com/avrdudes/avrdude

**Comment by wb0gaz** [comment]
Created at URL below and closed here with comment.

https://github.com/avrdudes/avrdude/issues/871
